Test logic
device-automation-bus/dab-compliance-suite pull request #42
Opened 2024-01-15 21:47 UTC by bgy36ww

Update Test logic to dynamic determine results based on list operations

2024-01-16 22:17 UTC, xhaakon requested changes

2024-01-16 22:17 UTC, xhaakon commented on dab/system.py
> +    elif response['status'] != 200:
`EnforcementManager().is_setting_supported(request.system_setting_key)` fails with `AttributeError: 'dict' object has no attribute 'system_setting_key'`.

If I get [DAB 2.0 specification of `/system/settings/get`](https://github.com/device-automation-bus/dab-specification-2.0/blob/main/DAB.md#operation-getting-system-settings) right, you don't specify which setting(s) you want to get and you always retrieve _all_ settings values in the reply. You'll therefore never see a 501 response and it is pointless to check for it. I suggest reverting this change.
```suggestion
    if response['status'] != 200:
```

2024-01-18 16:39 UTC, xhaakon requested changes

2024-01-18 16:39 UTC, xhaakon commented on util/enforcement_manager.py
> +        return "Alexa" if len(self.supported_voice_assistants) == 0 else self.supported_voice_assistants[0]
The name should be `AmazonAlexa` according to [DAB 2.0](https://github.com/device-automation-bus/dab-specification-2.0/blob/main/DAB.md#voice-system-name-registry).
```suggestion
        return "AmazonAlexa" if len(self.supported_voice_assistants) == 0 else self.supported_voice_assistants[0]
```

2024-02-08 00:21 UTC, bgy36ww commented
Hey Jakub Adam,

Thanks for the review, I caught COVID. And couldn't get back to this PR.

2024-02-08 17:54 UTC, xhaakon requested changes
Hello Wei, I'm sorry to hear about your health issues. Hope you're already feeling better.

I found a couple more issues with this pull request.

2024-02-08 17:54 UTC, xhaakon commented on util/enforcement_manager.py
> +            return True
I'm getting `AttributeError: 'dict' object has no attribute 'language'` here.

```suggestion
        if isinstance(self.supported_settings.get(setting), List) and len(self.supported_settings.get(setting)) == 0:
            return True

        if isinstance(self.supported_settings.get(setting), bool) and self.supported_settings.get(setting):
            return True
```

2024-02-08 17:54 UTC, xhaakon commented on voice_text.py
> +    ("voice/send-text",f'{{"requestText" : "Press enter", "voiceSystem": "{EnforcementManager().get_voice_assistant()}"}}', dab.voice.send_text, "Is video playing?", "Voice play video", "Voice play v
There seems to be redundant value at the end of the tuple causing this error when I try to list available test cases:

```
  File "/home/collabora/ws/GOO/dab-compliance-suite/main.py", line 85, in <module>
    (dab_request_topic, dab_request_body, validate_output_function, expected_response, test_title) = test_case
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 5)
```

```suggestion
    ("voice/send-text",f'{{"requestText" : "Press enter", "voiceSystem": "{EnforcementManager().get_voice_assistant()}"}}', dab.voice.send_text, "Is video playing?", "Voice play video"),
```

2024-02-08 18:03 UTC, xhaakon commented
On top of that validation of `/system/settings/set` responses is failing:

```
testing system/settings/set   {"memc": true} ... [ 
Error: self.dab_client.last_error_code()
Request invalid or malformed ]

testing system/settings/set   {"cec": true} ... Schema error: 'system_setting_key' is a required property

Failed validating 'required' in schema:
    {'properties': {'error': {'type': ['string', 'null']},
                    'status': {'type': 'integer'},
                    'system_setting_key': {'type': 'string'},
                    'value': {}},
     'required': ['status', 'system_setting_key', 'value'],
     'type': 'object'}

On instance:
    {'status': 200}
[ FAILED ]
```

I think it's because the conformance suite has a wrong JSON schema of the reply; there's no `"system_setting_key"` in the actual messages. You can try my suggested fix in this commit: https://github.com/device-automation-bus/dab-compliance-suite/commit/8a953a19ccf05986bbdd0cd085e8fef1fe9a3604.

2024-02-12 23:38 UTC, bgy36ww commented
> On top of that validation of `/system/settings/set` responses is failing:
> 
> ```
> testing system/settings/set   {"memc": true} ... [ 
> Error: self.dab_client.last_error_code()
> Request invalid or malformed ]
> 
> testing system/settings/set   {"cec": true} ... Schema error: 'system_setting_key' is a required property
> 
> Failed validating 'required' in schema:
>     {'properties': {'error': {'type': ['string', 'null']},
>                     'status': {'type': 'integer'},
>                     'system_setting_key': {'type': 'string'},
>                     'value': {}},
>      'required': ['status', 'system_setting_key', 'value'],
>      'type': 'object'}
> 
> On instance:
>     {'status': 200}
> [ FAILED ]
> ```
> 
> I think it's because the conformance suite has a wrong JSON schema of the reply; there's no `"system_setting_key"` in the actual messages. You can try my suggested fix in this commit: [8a953a1](https://github.com/device-automation-bus/dab-compliance-suite/commit/8a953a19ccf05986bbdd0cd085e8fef1fe9a3604).

https://github.com/device-automation-bus/dab-specification-2.0?tab=readme-ov-file#operation-setting-system-settings
Oh this part I am confused. WDYM?

2024-02-13 00:22 UTC, xhaakon commented
On 13. 02. 24 0:38, Wei Wang wrote:
> https://github.com/device-automation-bus/dab-specification-2.0?tab=readme-ov-file#operation-setting-system-settings 
> Oh this part I am confused. WDYM?

I agree this request format isn't defined very clearly:

interface SetSystemSettingsRequest extends DabRequest {
    [system_setting_key: keyof SystemSettings]: [value: any];
}

First of all I think instead of SystemSettings (which isn't defined anywhere in DAB spec) it should rather
reference GetCurrentSystemSettingsResponse inferface, like this:

interface SetSystemSettingsRequest extends DabRequest {
    [system_setting_key: keyof GetCurrentSystemSettingsResponse]: [value: any];
}

where [system_setting_key: keyof GetCurrentSystemSettingsResponse] says that SetSystemSettingsRequest
can contain properties of the same names as in GetCurrentSystemSettingsResponse. It's a more succinct
(and, arguably, confusing) way of writing:

interface SetSystemSettingsRequest extends DabRequest {
    language?: rfc_5646_language_tag;
    outputResolution?: OutputResolution;
    memc?: boolean;
    cec?: boolean;
    lowLatencyMode?: boolean;
    matchContentFrameRate?: MatchContentFrameRate;
    hdrOutputMode?: HdrOutputMode;
    pictureMode?: PictureMode;
    audioOutputMode?: AudioOutputMode;
    audioOutputSource?: AudioOutputSource;
    videoInputSource?: VideoInputSource;
    audioVolume?: int;
    mute?: boolean;
    textToSpeech?: boolean;
}

An example /system/settings/set request that changes outputResolution and audioVolume could then look like this:

{
    "outputResolution": {
       "width": 3840,
       "height": 2160,
       "frequency": 60
    },
    "audioVolume": 50
}

2024-02-13 00:43 UTC, xhaakon requested changes

2024-02-13 00:43 UTC, xhaakon commented on schema.py
> +    "unevaluatedProperties": False
Missing closing curly bracket
```suggestion
    "unevaluatedProperties": False
}
```

2024-02-13 00:48 UTC, GaganBhat commented
Agreed @xhaakon, the set systems request should only be able to set a system setting that the device is capable of getting in the first place.

However, when certifying we expect the DAB device to respond to all system setting options (even if it doesn't support it) by responding appropriately (501 not implemented) with any message of their choosing so that the client understands the reason for why their set failed.

2024-02-13 00:59 UTC, GaganBhat commented
Additionally, I'm not sure if this PR consists of this:

But we need to verify that after doing a `set` operation, the `get` of that same property reflects the change as we expect.

We're seeing on some partner platforms that they return `200 successful` on a `set`, but once you `get` that same property it's not reflected correctly.

This will catch issues when the partner implementations for set system settings does not work as expected.

2024-02-13 02:53 UTC, bgy36ww commented
> Additionally, I'm not sure if this PR consists of this:
> 
> But we need to verify that after doing a `set` operation, the `get` of that same property reflects the change as we expect.
> 
> We're seeing on some partner platforms that they return `200 successful` on a `set`, but once you `get` that same property it's not reflected correctly.
> 
> This will catch issues when the partner implementations for set system settings does not work as expected.

That would require a functional test. I think let's get the basic topic calls merge first.

2024-02-26 05:09 UTC, bgy36ww commented
@xhaakon Need your approval.

2024-02-26 14:18 UTC, xhaakon requested changes
I found one more issue (in my own code, sorry). Otherwise LGTM.

2024-02-26 14:18 UTC, xhaakon commented on schema.py
> +        "required": system_settings_schema.keys()
This is my mistake here; `dict.keys()` returns a "view object", whereas jsonschema expects an array type as value of `"required"`. The suggestion below fixes this error:
```
Schema error: dict_keys(['language', 'outputResolution', 'memc', 'cec', 'lowLatencyMode', 'matchContentFrameRate', 'hdrOutputMode', 'pictureMode', 'audioOutputMode', 'audioOutputSource', 'videoInputSource', 'audioVolume', 'mute', 'textToSpeech']) is not of type 'array'
```

```suggestion
        "required": list(system_settings_schema.keys())
```

2024-03-05 16:51 UTC, bgy36ww commented
Need LGTM from someone.

2024-03-12 21:45 UTC, merged