fixes isssues/3
device-automation-bus/dab-compliance-suite pull request #7
Opened 2023-06-27 23:32 UTC by bgy36ww

2023-06-28 00:32 UTC, GaganBhat commented
@bgy36ww Could we add a comment in the README that the partner has to fix their config dict before running the test?

2023-06-28 00:33 UTC, GaganBhat requested changes

2023-06-28 00:33 UTC, GaganBhat commented on config.py
> +# Please config the app display name here.
Maybe we can be explicit that the _values_ are the ones that should be changed to their respective names

2023-06-29 05:17 UTC, akshaygarg86 commented on main.py
>      ("output/image",'{"outputLocation": "https://webhook.site/791918a1-cf5f-4a3e-9166-9f83af776232"}', dab.output.image, 2000),
do you need to change this test case for output image as well?

2023-06-29 18:21 UTC, GaganBhat approved these changes

2023-06-29 18:25 UTC, merged